### ISSUE TITLE
Can not send message as a bot

### ISSUE THREAD

**Issue by volodalexey** [airgram/airgram#10]
I want to implement e2e test (send message as a user and as a bot).
I created [repo](https://github.com/volodalexey/airgram-user-and-bot-test) to reproduce the issue.

Looks like I can not send message as a bot, I get:
```
 console.error node_modules/airgram/base/Logger.js:105
console.error node_modules/airgram/base/Logger.js:105
    [messages.sendMessage]: "CODE#400 PEER_ID_INVALID"  {
      "stack": "CODE#400 PEER_ID_INVALID\n
at MtpClient.Object.<anonymous>.MtpClient.createError (.../node_modules/src/base/MtpClient.ts:283:12)\n
at MtpClient.Object.<anonymous>.MtpClient.handleResponse (...node_modules/src/base/MtpClient.ts:491:32)\n
at MtpClient.Object.<anonymous>.MtpClient.handleResponse (...node_modules/src/base/MtpClient.ts:410:14)\n
at MtpClient.Object.<anonymous>.MtpClient.handleResponse (...node_modules/src/base/MtpClient.ts:349:16)\n
at ...node_modules/src/base/MtpClient.ts:829:12\n
at <anonymous>\n
at process._tickCallback (internal/process/next_tick.js:189:7)"
    }
```

**Comment by esindger** [comment]
Please check out the [pull request](https://github.com/volodalexey/airgram-user-and-bot-test/pull/1). Now it works.

**Comment by esindger** [comment]
And check if the `Allow groups` option is turned on for your bot.

**Comment by volodalexey** [comment]
Thanks! It works!

**Comment by volodalexey** [comment]
@esindger Can you explain how to se Auth middleware correctly? I do not undestand [this comment](https://github.com/volodalexey/airgram-user-and-bot-test/blob/3045b4fe2ce471c137171f188b1b641aa265bbb2/src/app.ts#L31).
I have two separated instances of Airgram. And I initialize Auth middleware for both of them, so it should be any intersection between each other.

**Comment by esindger** [comment]
You call the function `createApp` and `authorizeApp` right [next to each other](https://github.com/volodalexey/airgram-user-and-bot-test/blob/3045b4fe2ce471c137171f188b1b641aa265bbb2/src/user.authorize.ts#L8-L9). If to expand both functions we will see something like that:

```
// function createApp()
let airgram: Airgram

// ...

const { auth } = airgram
airgram.use(auth)

auth.use(new AuthDialog({
  firstName: '',
  lastName: '',
  phoneNumber: config.phone_number,
  // ...
}))

// function authorizeApp()
airgram.auth.use(new AuthDialog({
  firstName: '',
  lastName: '',
  phoneNumber: config.phone_number,
  // ...
}));

return airgram.auth.login()
```

As you can see you double call `airgram.auth.use(new AuthDialog())`, that is unnecessary.

This [line](https://github.com/volodalexey/airgram-user-and-bot-test/blob/3045b4fe2ce471c137171f188b1b641aa265bbb2/src/app.ts#L35) should not be commented. That's a typo.

**Comment by volodalexey** [comment]
Ok. I got it. It is related to my "authorize" scipts. Thanks.

Again get back to my initial problem.
As a bot - I do not see any updates/messages from user.
I updated my code [here](https://github.com/volodalexey/airgram-user-and-bot-test/tree/3f080170fb4e169853c6a9c0bd706004f04da83a).
I start polling as a [bot](https://github.com/volodalexey/airgram-user-and-bot-test/blob/3f080170fb4e169853c6a9c0bd706004f04da83a/src/test.ts#L23).
I send "/start" command as a user and I want to receive this command/message as a bot.
But bot - keeps silence, neither [this](https://github.com/volodalexey/airgram-user-and-bot-test/blob/3f080170fb4e169853c6a9c0bd706004f04da83a/src/app.ts#L43) or [this](https://github.com/volodalexey/airgram-user-and-bot-test/blob/3f080170fb4e169853c6a9c0bd706004f04da83a/src/app.ts#L50) work.

**Comment by esindger** [comment]
You forgot to [apply](https://github.com/esindger/airgram-user-and-bot-test/blob/master/src/app.ts#L47) `Update` middleware: `airgram.use(updates)`

**Comment by volodalexey** [comment]
My fault. Thanks.
